name: Django Tests

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

# on:
#     schedule:
#         - cron: '*/15 * * * *'

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up python 3.8
              uses: actions/setup-python@v3
              with:
                python-version: 3.8
            - name: Install dependencies
              run:
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Lint with flake8
              run:
                pip install flake8
                flake8
            - name: Install specific version of run package
              run:
                pip install  --upgrade run
            - name: Coverage report
              run:
                pip install coverage
                coverage run manage.py test
                coverage report
            - name: Django Testing
              run:
                python3 manage.py test
